---
- name: "Installing obs-studio through snap - https://snapcraft.io/install/obs-studio/ubuntu"
  become: yes
  snap:
    name: obs-studio

- name: "Connecting Interfaces"
  become: yes
  command: snap connect obs-studio:{{ item }}
  loop:
    - alsa
    - audio-record
    - camera
    - jack1
    - kernel-module-observe

- name: "Setting up Virtual Camera"
  become: yes
  apt:
    name: "{{item}}"
    update_cache: yes
    state: present
  loop:
    - v4l2loopback-dkms
    - v4l2loopback-utils

- name: Setting up Virtual Camera plugins
  become: yes
  shell: |
    echo "options v4l2loopback devices=1 video_nr=13 card_label='OBS Virtual Camera'    exclusive_caps=1" | sudo tee /etc/modprobe.d/v4l2loopback.conf
    echo "v4l2loopback" | sudo tee /etc/modules-load.d/v4l2loopback.conf
    sudo modprobe -r v4l2loopback
    sudo modprobe v4l2loopback devices=1 video_nr=13 card_label='OBS Virtual Camera' exclusive_caps=1