---
- name: "Installing nodejs through snap - https://snapcraft.io/install/node/ubuntu"
  become: yes
  snap:
    name: node
    classic: yes

- name: "Installing  yarn with corepack - npm i -g corepack"
  become: yes
  shell: sudo npm i -g corepack